//------------------------------------------------------------------------------
// <auto-generated>
//     Hand-maintained strongly-typed resource accessor (dotnet build does not run
//     the VS ResX generator). Keep in sync with NavigationResources.resx.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DayDash.Modules.Settings.Resources;

#nullable enable

using System.Globalization;
using System.Resources;

[System.CodeDom.Compiler.GeneratedCode("DayDash", "1.0")]
[System.Diagnostics.DebuggerNonUserCode]
public class NavigationResources
{
    private static ResourceManager? _resourceMan;

    internal NavigationResources() { }

    public static ResourceManager ResourceManager =>
        _resourceMan ??= new ResourceManager("DayDash.Modules.Settings.Resources.NavigationResources", typeof(NavigationResources).Assembly);

    public static CultureInfo? Culture { get; set; }

    public static string BrandName => ResourceManager.GetString("BrandName", Culture) ?? "BrandName";
    public static string Calendar => ResourceManager.GetString("Calendar", Culture) ?? "Calendar";
    public static string StudyPlan => ResourceManager.GetString("StudyPlan", Culture) ?? "StudyPlan";
    public static string Camera => ResourceManager.GetString("Camera", Culture) ?? "Camera";
    public static string Settings => ResourceManager.GetString("Settings", Culture) ?? "Settings";
    public static string ToggleNavigation => ResourceManager.GetString("ToggleNavigation", Culture) ?? "ToggleNavigation";
    public static string NotFoundTitle => ResourceManager.GetString("NotFoundTitle", Culture) ?? "NotFoundTitle";
    public static string NotFoundMessage => ResourceManager.GetString("NotFoundMessage", Culture) ?? "NotFoundMessage";
}
