//------------------------------------------------------------------------------
// <auto-generated>
//     Hand-maintained strongly-typed resource accessor (dotnet build does not run
//     the VS ResX generator). Keep in sync with SettingsResources.resx.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DayDash.Modules.Settings.Resources;

using System.Globalization;
using System.Resources;

[System.CodeDom.Compiler.GeneratedCode("DayDash", "1.0")]
[System.Diagnostics.DebuggerNonUserCode]
public class SettingsResources
{
    private static ResourceManager? _resourceMan;

    internal SettingsResources() { }

    public static ResourceManager ResourceManager =>
        _resourceMan ??= new ResourceManager("DayDash.Modules.Settings.Resources.SettingsResources", typeof(SettingsResources).Assembly);

    public static CultureInfo? Culture { get; set; }

    public static string PageTitle => ResourceManager.GetString("PageTitle", Culture) ?? "PageTitle";
    public static string SettingsTitle => ResourceManager.GetString("SettingsTitle", Culture) ?? "SettingsTitle";
    public static string Language => ResourceManager.GetString("Language", Culture) ?? "Language";
    public static string LanguageGerman => ResourceManager.GetString("LanguageGerman", Culture) ?? "LanguageGerman";
    public static string LanguageEnglish => ResourceManager.GetString("LanguageEnglish", Culture) ?? "LanguageEnglish";
    public static string Appearance => ResourceManager.GetString("Appearance", Culture) ?? "Appearance";
    public static string ThemeLight => ResourceManager.GetString("ThemeLight", Culture) ?? "ThemeLight";
    public static string ThemeDark => ResourceManager.GetString("ThemeDark", Culture) ?? "ThemeDark";
    public static string EventTypeSettings => ResourceManager.GetString("EventTypeSettings", Culture) ?? "EventTypeSettings";
    public static string SubjectSettings => ResourceManager.GetString("SubjectSettings", Culture) ?? "SubjectSettings";
    public static string ReminderSettings => ResourceManager.GetString("ReminderSettings", Culture) ?? "ReminderSettings";
    public static string Save => ResourceManager.GetString("Save", Culture) ?? "Save";
    public static string Saved => ResourceManager.GetString("Saved", Culture) ?? "Saved";
    public static string Cancel => ResourceManager.GetString("Cancel", Culture) ?? "Cancel";
    public static string DatabaseErrorTitle => ResourceManager.GetString("DatabaseErrorTitle", Culture) ?? "DatabaseErrorTitle";
    public static string DatabaseErrorMessage => ResourceManager.GetString("DatabaseErrorMessage", Culture) ?? "DatabaseErrorMessage";
}
