//------------------------------------------------------------------------------
// <auto-generated>
//     Hand-maintained strongly-typed accessor. Keep in sync with ReminderResources.resx.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DayDash.Modules.Reminder.Resources;

#nullable enable

using System.Globalization;
using System.Resources;

[System.CodeDom.Compiler.GeneratedCode("DayDash", "1.0")]
[System.Diagnostics.DebuggerNonUserCode]
public class ReminderResources
{
    private static ResourceManager? _resourceMan;

    internal ReminderResources() { }

    public static ResourceManager ResourceManager => _resourceMan ??=
        new ResourceManager("DayDash.Modules.Reminder.Resources.ReminderResources", typeof(ReminderResources).Assembly);

    public static CultureInfo? Culture { get; set; }

    public static string PageTitle => ResourceManager.GetString("PageTitle", Culture) ?? "PageTitle";
    public static string ReminderSettings => ResourceManager.GetString("ReminderSettings", Culture) ?? "ReminderSettings";
    public static string DailyStudyReminderTime => ResourceManager.GetString("DailyStudyReminderTime", Culture) ?? "DailyStudyReminderTime";
    public static string EventReminderDaysBefore => ResourceManager.GetString("EventReminderDaysBefore", Culture) ?? "EventReminderDaysBefore";
    public static string IsEnabled => ResourceManager.GetString("IsEnabled", Culture) ?? "IsEnabled";
    public static string EnableNotifications => ResourceManager.GetString("EnableNotifications", Culture) ?? "EnableNotifications";
    public static string Save => ResourceManager.GetString("Save", Culture) ?? "Save";
    public static string Saved => ResourceManager.GetString("Saved", Culture) ?? "Saved";
    public static string NotificationsUnavailable => ResourceManager.GetString("NotificationsUnavailable", Culture) ?? "NotificationsUnavailable";
    public static string NotificationChannelName => ResourceManager.GetString("NotificationChannelName", Culture) ?? "NotificationChannelName";
    public static string NotificationChannelDescription => ResourceManager.GetString("NotificationChannelDescription", Culture) ?? "NotificationChannelDescription";
    public static string DailyStudyReminderTitle => ResourceManager.GetString("DailyStudyReminderTitle", Culture) ?? "DailyStudyReminderTitle";
    public static string DailyStudyReminderBody => ResourceManager.GetString("DailyStudyReminderBody", Culture) ?? "DailyStudyReminderBody";
    public static string DailyStudyReminderBodyMultiple => ResourceManager.GetString("DailyStudyReminderBodyMultiple", Culture) ?? "DailyStudyReminderBodyMultiple";
    public static string EventReminderTitle => ResourceManager.GetString("EventReminderTitle", Culture) ?? "EventReminderTitle";
    public static string EventReminderBody => ResourceManager.GetString("EventReminderBody", Culture) ?? "EventReminderBody";
}
