//------------------------------------------------------------------------------
// <auto-generated>
//     Localization anchor for the Reminder module. Reminder consumes its strings through
//     IStringLocalizer<ReminderResources>, so only the ResourceManager hook is needed.
//     Translations live in ReminderResources.resx (de-CH) and ReminderResources.en.resx.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DayDash.Modules.Reminder.Resources;

#nullable enable

using System.Globalization;
using System.Resources;

[System.CodeDom.Compiler.GeneratedCode("DayDash", "1.0")]
[System.Diagnostics.DebuggerNonUserCode]
public class ReminderResources
{
    private static ResourceManager? _resourceMan;

    internal ReminderResources() { }

    public static ResourceManager ResourceManager => _resourceMan ??=
        new ResourceManager("DayDash.Modules.Reminder.Resources.ReminderResources", typeof(ReminderResources).Assembly);

    public static CultureInfo? Culture { get; set; }
}
