//------------------------------------------------------------------------------
// <auto-generated>
//     Hand-maintained strongly-typed accessor. Keep in sync with CameraResources.resx.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DayDash.Modules.Camera.Resources;

#nullable enable

using System.Globalization;
using System.Resources;

[System.CodeDom.Compiler.GeneratedCode("DayDash", "1.0")]
[System.Diagnostics.DebuggerNonUserCode]
public class CameraResources
{
    private static ResourceManager? _resourceMan;

    internal CameraResources() { }

    public static ResourceManager ResourceManager => _resourceMan ??=
        new ResourceManager("DayDash.Modules.Camera.Resources.CameraResources", typeof(CameraResources).Assembly);

    public static CultureInfo? Culture { get; set; }

    public static string PageTitle => ResourceManager.GetString("PageTitle", Culture) ?? "PageTitle";
    public static string CameraTitle => ResourceManager.GetString("CameraTitle", Culture) ?? "CameraTitle";
    public static string CapturePhoto => ResourceManager.GetString("CapturePhoto", Culture) ?? "CapturePhoto";
    public static string Recognizing => ResourceManager.GetString("Recognizing", Culture) ?? "Recognizing";
    public static string ParsedGoals => ResourceManager.GetString("ParsedGoals", Culture) ?? "ParsedGoals";
    public static string NothingRecognized => ResourceManager.GetString("NothingRecognized", Culture) ?? "NothingRecognized";
    public static string CameraNotAvailable => ResourceManager.GetString("CameraNotAvailable", Culture) ?? "CameraNotAvailable";
    public static string PermissionDenied => ResourceManager.GetString("PermissionDenied", Culture) ?? "PermissionDenied";
    public static string CaptureCancelled => ResourceManager.GetString("CaptureCancelled", Culture) ?? "CaptureCancelled";
    public static string RecognitionFailed => ResourceManager.GetString("RecognitionFailed", Culture) ?? "RecognitionFailed";
    public static string Retake => ResourceManager.GetString("Retake", Culture) ?? "Retake";
    public static string SelectExam => ResourceManager.GetString("SelectExam", Culture) ?? "SelectExam";
    public static string NoExamSelected => ResourceManager.GetString("NoExamSelected", Culture) ?? "NoExamSelected";
    public static string LoadFailed => ResourceManager.GetString("LoadFailed", Culture) ?? "LoadFailed";
    public static string AttachToExam => ResourceManager.GetString("AttachToExam", Culture) ?? "AttachToExam";
    public static string GoalsSaved => ResourceManager.GetString("GoalsSaved", Culture) ?? "GoalsSaved";
    public static string GoalsSaveFailed => ResourceManager.GetString("GoalsSaveFailed", Culture) ?? "GoalsSaveFailed";
    public static string AddRow => ResourceManager.GetString("AddRow", Culture) ?? "AddRow";
    public static string DeleteRow => ResourceManager.GetString("DeleteRow", Culture) ?? "DeleteRow";
    public static string MoveUp => ResourceManager.GetString("MoveUp", Culture) ?? "MoveUp";
    public static string MoveDown => ResourceManager.GetString("MoveDown", Culture) ?? "MoveDown";
    public static string SaveGoals => ResourceManager.GetString("SaveGoals", Culture) ?? "SaveGoals";
}
