//------------------------------------------------------------------------------
// <auto-generated>
//     Localization anchor for the Camera module. Camera consumes its strings through
//     IStringLocalizer<CameraResources>, so only the ResourceManager hook is needed.
//     Translations live in CameraResources.resx (de-CH) and CameraResources.en.resx.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DayDash.Modules.Camera.Resources;

#nullable enable

using System.Globalization;
using System.Resources;

[System.CodeDom.Compiler.GeneratedCode("DayDash", "1.0")]
[System.Diagnostics.DebuggerNonUserCode]
public class CameraResources
{
    private static ResourceManager? _resourceMan;

    internal CameraResources() { }

    public static ResourceManager ResourceManager => _resourceMan ??=
        new ResourceManager("DayDash.Modules.Camera.Resources.CameraResources", typeof(CameraResources).Assembly);

    public static CultureInfo? Culture { get; set; }
}
