//------------------------------------------------------------------------------
// <auto-generated>
//     Hand-maintained strongly-typed accessor. Keep in sync with StudyPlannerResources.resx.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DayDash.Modules.StudyPlanner.Resources;

using System.Globalization;
using System.Resources;

[System.CodeDom.Compiler.GeneratedCode("DayDash", "1.0")]
[System.Diagnostics.DebuggerNonUserCode]
public class StudyPlannerResources
{
    private static ResourceManager? _resourceMan;
    internal StudyPlannerResources() { }
    public static ResourceManager ResourceManager => _resourceMan ??= new ResourceManager("DayDash.Modules.StudyPlanner.Resources.StudyPlannerResources", typeof(StudyPlannerResources).Assembly);
    public static CultureInfo? Culture { get; set; }
    public static string CreateExam => ResourceManager.GetString("CreateExam", Culture) ?? "CreateExam";
    public static string Title => ResourceManager.GetString("Title", Culture) ?? "Title";
    public static string Subject => ResourceManager.GetString("Subject", Culture) ?? "Subject";
    public static string ExamDate => ResourceManager.GetString("ExamDate", Culture) ?? "ExamDate";
    public static string TotalStudyMinutes => ResourceManager.GetString("TotalStudyMinutes", Culture) ?? "TotalStudyMinutes";
    public static string Recommendation => ResourceManager.GetString("Recommendation", Culture) ?? "Recommendation";
    public static string Minutes => ResourceManager.GetString("Minutes", Culture) ?? "Minutes";
    public static string Save => ResourceManager.GetString("Save", Culture) ?? "Save";
    public static string ExamDetails => ResourceManager.GetString("ExamDetails", Culture) ?? "ExamDetails";
    public static string DaysRemaining => ResourceManager.GetString("DaysRemaining", Culture) ?? "DaysRemaining";
    public static string MinutesToday => ResourceManager.GetString("MinutesToday", Culture) ?? "MinutesToday";
    public static string LearningGoals => ResourceManager.GetString("LearningGoals", Culture) ?? "LearningGoals";
    public static string Edit => ResourceManager.GetString("Edit", Culture) ?? "Edit";
    public static string Delete => ResourceManager.GetString("Delete", Culture) ?? "Delete";
    public static string SubjectConfig => ResourceManager.GetString("SubjectConfig", Culture) ?? "SubjectConfig";
    public static string Actions => ResourceManager.GetString("Actions", Culture) ?? "Actions";
    public static string AddSubject => ResourceManager.GetString("AddSubject", Culture) ?? "AddSubject";
    public static string TodayStudyPlan => ResourceManager.GetString("TodayStudyPlan", Culture) ?? "TodayStudyPlan";
    public static string Study => ResourceManager.GetString("Study", Culture) ?? "Study";
    public static string DefaultSubject_Math => ResourceManager.GetString("DefaultSubject_Math", Culture) ?? "DefaultSubject_Math";
    public static string DefaultSubject_German => ResourceManager.GetString("DefaultSubject_German", Culture) ?? "DefaultSubject_German";
    public static string DefaultSubject_Nmg => ResourceManager.GetString("DefaultSubject_Nmg", Culture) ?? "DefaultSubject_Nmg";
    public static string DefaultSubject_English => ResourceManager.GetString("DefaultSubject_English", Culture) ?? "DefaultSubject_English";
    public static string DefaultSubject_French => ResourceManager.GetString("DefaultSubject_French", Culture) ?? "DefaultSubject_French";
    public static string MinutesPerGoal => ResourceManager.GetString("MinutesPerGoal", Culture) ?? "MinutesPerGoal";
    public static string NewSubject => ResourceManager.GetString("NewSubject", Culture) ?? "NewSubject";
    public static string PageTitle => ResourceManager.GetString("PageTitle", Culture) ?? "PageTitle";
    public static string StudyPlanTitle => ResourceManager.GetString("StudyPlanTitle", Culture) ?? "StudyPlanTitle";
    public static string ExamList => ResourceManager.GetString("ExamList", Culture) ?? "ExamList";
    public static string NewExam => ResourceManager.GetString("NewExam", Culture) ?? "NewExam";
    public static string EditExam => ResourceManager.GetString("EditExam", Culture) ?? "EditExam";
    public static string DeleteExam => ResourceManager.GetString("DeleteExam", Culture) ?? "DeleteExam";
    public static string ConfirmDeleteExam => ResourceManager.GetString("ConfirmDeleteExam", Culture) ?? "ConfirmDeleteExam";
    public static string Cancel => ResourceManager.GetString("Cancel", Culture) ?? "Cancel";
    public static string NoExams => ResourceManager.GetString("NoExams", Culture) ?? "NoExams";
    public static string AddGoal => ResourceManager.GetString("AddGoal", Culture) ?? "AddGoal";
    public static string GoalText => ResourceManager.GetString("GoalText", Culture) ?? "GoalText";
    public static string RemoveGoal => ResourceManager.GetString("RemoveGoal", Culture) ?? "RemoveGoal";
    public static string TotalMinutesToday => ResourceManager.GetString("TotalMinutesToday", Culture) ?? "TotalMinutesToday";
    public static string NoStudyToday => ResourceManager.GetString("NoStudyToday", Culture) ?? "NoStudyToday";
    public static string ExamAssistant => ResourceManager.GetString("ExamAssistant", Culture) ?? "ExamAssistant";
    public static string StepSubject => ResourceManager.GetString("StepSubject", Culture) ?? "StepSubject";
    public static string StepGoals => ResourceManager.GetString("StepGoals", Culture) ?? "StepGoals";
    public static string StepMinutes => ResourceManager.GetString("StepMinutes", Culture) ?? "StepMinutes";
    public static string Next => ResourceManager.GetString("Next", Culture) ?? "Next";
    public static string Back => ResourceManager.GetString("Back", Culture) ?? "Back";
    public static string Finish => ResourceManager.GetString("Finish", Culture) ?? "Finish";
    public static string TitleRequired => ResourceManager.GetString("TitleRequired", Culture) ?? "TitleRequired";
    public static string SubjectRequired => ResourceManager.GetString("SubjectRequired", Culture) ?? "SubjectRequired";
    public static string MinutesRange => ResourceManager.GetString("MinutesRange", Culture) ?? "MinutesRange";
    public static string Overdue => ResourceManager.GetString("Overdue", Culture) ?? "Overdue";
    public static string TodayLabel => ResourceManager.GetString("TodayLabel", Culture) ?? "TodayLabel";
    public static string TomorrowLabel => ResourceManager.GetString("TomorrowLabel", Culture) ?? "TomorrowLabel";
    public static string SubjectDeletedFallback => ResourceManager.GetString("SubjectDeletedFallback", Culture) ?? "SubjectDeletedFallback";
    public static string Saved => ResourceManager.GetString("Saved", Culture) ?? "Saved";
    public static string Days => ResourceManager.GetString("Days", Culture) ?? "Days";
    public static string SaveFailed => ResourceManager.GetString("SaveFailed", Culture) ?? "SaveFailed";
}
