//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DayDash.Modules.StudyPlanner.Resources {
    using System;
    using System.Reflection;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StudyPlannerResources {

        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("DayDash.Modules.StudyPlanner.Resources.StudyPlannerResources", typeof(StudyPlannerResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string CreateExam {
            get {
                return ResourceManager.GetString("CreateExam", resourceCulture);
            }
        }

        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }

        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }

        public static string ExamDate {
            get {
                return ResourceManager.GetString("ExamDate", resourceCulture);
            }
        }

        public static string TotalStudyMinutes {
            get {
                return ResourceManager.GetString("TotalStudyMinutes", resourceCulture);
            }
        }

        public static string Recommendation {
            get {
                return ResourceManager.GetString("Recommendation", resourceCulture);
            }
        }

        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }

        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }

        public static string ExamDetails {
            get {
                return ResourceManager.GetString("ExamDetails", resourceCulture);
            }
        }

        public static string DaysRemaining {
            get {
                return ResourceManager.GetString("DaysRemaining", resourceCulture);
            }
        }

        public static string MinutesToday {
            get {
                return ResourceManager.GetString("MinutesToday", resourceCulture);
            }
        }

        public static string LearningGoals {
            get {
                return ResourceManager.GetString("LearningGoals", resourceCulture);
            }
        }

        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }

        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }

        public static string SubjectConfig {
            get {
                return ResourceManager.GetString("SubjectConfig", resourceCulture);
            }
        }

        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }

        public static string AddSubject {
            get {
                return ResourceManager.GetString("AddSubject", resourceCulture);
            }
        }

        public static string TodayStudyPlan {
            get {
                return ResourceManager.GetString("TodayStudyPlan", resourceCulture);
            }
        }

        public static string Study {
            get {
                return ResourceManager.GetString("Study", resourceCulture);
            }
        }
    }
}