// <auto-generated />
using System;
using DayDash.Modules.Storage.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DayDash.Migrations.Migrations
{
    [DbContext(typeof(DayDashDbContext))]
    [Migration("20260831035638_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("DayDash.Modules.Calendar.Domain.CalendarEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EventTypeId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAllDay")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("LinkedExamId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly?>("TimeFrom")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly?>("TimeTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("EventTypeId");

                    b.HasIndex("LinkedExamId");

                    b.ToTable("CalendarEvents", (string)null);
                });

            modelBuilder.Entity("DayDash.Modules.Calendar.Domain.EventTypeConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasFilter("\"Key\" <> ''");

                    b.ToTable("EventTypeConfigs", (string)null);
                });

            modelBuilder.Entity("DayDash.Modules.Reminder.Domain.ReminderConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("DailyStudyReminderTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("EventReminderDaysBefore")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ReminderConfigs", (string)null);
                });

            modelBuilder.Entity("DayDash.Modules.StudyPlanner.Domain.Exam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("DailyMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("ExamDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("RecommendedMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalStudyMinutes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExamDate");

                    b.ToTable("Exams", (string)null);
                });

            modelBuilder.Entity("DayDash.Modules.StudyPlanner.Domain.LearningGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsChecked")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExamId", "SortOrder");

                    b.ToTable("LearningGoals", (string)null);
                });

            modelBuilder.Entity("DayDash.Modules.StudyPlanner.Domain.SubjectConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("MinutesPerGoal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(15);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SubjectConfigs", (string)null);
                });

            modelBuilder.Entity("DayDash.Modules.Calendar.Domain.CalendarEvent", b =>
                {
                    b.HasOne("DayDash.Modules.Calendar.Domain.EventTypeConfig", "EventType")
                        .WithMany()
                        .HasForeignKey("EventTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("EventType");
                });

            modelBuilder.Entity("DayDash.Modules.StudyPlanner.Domain.LearningGoal", b =>
                {
                    b.HasOne("DayDash.Modules.StudyPlanner.Domain.Exam", "Exam")
                        .WithMany("LearningGoals")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("DayDash.Modules.StudyPlanner.Domain.Exam", b =>
                {
                    b.Navigation("LearningGoals");
                });
#pragma warning restore 612, 618
        }
    }
}
