<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OverrideHtmlAssetPlaceholders>true</OverrideHtmlAssetPlaceholders>
    <BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" PrivateAssets="all" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
    <PackageReference Include="Microsoft.Extensions.Localization" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Modules\DayDash.Modules.Settings\DayDash.Modules.Settings.csproj" />
    <ProjectReference Include="..\Modules\DayDash.Modules.Storage\DayDash.Modules.Storage.csproj" />
    <ProjectReference Include="..\Modules\DayDash.Modules.Calendar\DayDash.Modules.Calendar.csproj" />
    <ProjectReference Include="..\Modules\DayDash.Modules.StudyPlanner\DayDash.Modules.StudyPlanner.csproj" />
    <ProjectReference Include="..\Modules\DayDash.Modules.Camera\DayDash.Modules.Camera.csproj" />
    <ProjectReference Include="..\Modules\DayDash.Modules.Reminder\DayDash.Modules.Reminder.csproj" />
    <ProjectReference Include="..\Modules\DayDash.Modules.Widget\DayDash.Modules.Widget.csproj" />
  </ItemGroup>

</Project>
