//------------------------------------------------------------------------------
// <auto-generated>
//     Hand-maintained strongly-typed accessor. Keep in sync with WidgetResources.resx.
//     The widgets run in a BroadcastReceiver with no DI, so they use this static
//     accessor with an explicit Culture instead of IStringLocalizer.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DayDash.Modules.Widget.Resources;

using System.Globalization;
using System.Resources;

[System.CodeDom.Compiler.GeneratedCode("DayDash", "1.0")]
[System.Diagnostics.DebuggerNonUserCode]
public static class WidgetResources
{
    private static ResourceManager? _resourceMan;

    public static ResourceManager ResourceManager => _resourceMan ??=
        new ResourceManager("DayDash.Modules.Widget.Resources.WidgetResources", typeof(WidgetResources).Assembly);

    /// <summary>Culture used for every lookup. Set once per widget update from the stored preference.</summary>
    public static CultureInfo? Culture { get; set; }

    private static string Get(string key) => ResourceManager.GetString(key, Culture) ?? key;

    public static string DayWidgetTitle => Get("DayWidgetTitle");
    public static string WeekWidgetTitle => Get("WeekWidgetTitle");
    public static string MonthWidgetTitle => Get("MonthWidgetTitle");
    public static string NextEvent => Get("NextEvent");
    public static string StudyPlan => Get("StudyPlan");
    public static string Minutes => Get("Minutes");
    public static string NoEventsToday => Get("NoEventsToday");
    public static string NoEventsThisWeek => Get("NoEventsThisWeek");
    public static string NoStudyToday => Get("NoStudyToday");
    public static string AllDay => Get("AllDay");
    public static string DataUnavailable => Get("DataUnavailable");
    public static string Weekday_Mon => Get("Weekday_Mon");
    public static string Weekday_Tue => Get("Weekday_Tue");
    public static string Weekday_Wed => Get("Weekday_Wed");
    public static string Weekday_Thu => Get("Weekday_Thu");
    public static string Weekday_Fri => Get("Weekday_Fri");
    public static string Weekday_Sat => Get("Weekday_Sat");
    public static string Weekday_Sun => Get("Weekday_Sun");

    /// <summary>Mon..Sun short names in display order, for the month grid header.</summary>
    public static string[] WeekdayHeadings =>
    [
        Weekday_Mon, Weekday_Tue, Weekday_Wed, Weekday_Thu, Weekday_Fri, Weekday_Sat, Weekday_Sun,
    ];
}
