//------------------------------------------------------------------------------
// <auto-generated>
//     Hand-maintained strongly-typed accessor. Keep in sync with CalendarResources.resx.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DayDash.Modules.Calendar.Resources;

using System.Globalization;
using System.Resources;

[System.CodeDom.Compiler.GeneratedCode("DayDash", "1.0")]
[System.Diagnostics.DebuggerNonUserCode]
public class CalendarResources
{
    private static ResourceManager? _resourceMan;
    internal CalendarResources() { }
    public static ResourceManager ResourceManager => _resourceMan ??= new ResourceManager("DayDash.Modules.Calendar.Resources.CalendarResources", typeof(CalendarResources).Assembly);
    public static CultureInfo? Culture { get; set; }
    public static string Previous => ResourceManager.GetString("Previous", Culture) ?? "Previous";
    public static string Next => ResourceManager.GetString("Next", Culture) ?? "Next";
    public static string Today => ResourceManager.GetString("Today", Culture) ?? "Today";
    public static string Date => ResourceManager.GetString("Date", Culture) ?? "Date";
    public static string Time => ResourceManager.GetString("Time", Culture) ?? "Time";
    public static string Notes => ResourceManager.GetString("Notes", Culture) ?? "Notes";
    public static string Edit => ResourceManager.GetString("Edit", Culture) ?? "Edit";
    public static string Delete => ResourceManager.GetString("Delete", Culture) ?? "Delete";
    public static string SelectDay => ResourceManager.GetString("SelectDay", Culture) ?? "SelectDay";
    public static string EventDetails => ResourceManager.GetString("EventDetails", Culture) ?? "EventDetails";
    public static string DefaultEventType_Exam => ResourceManager.GetString("DefaultEventType_Exam", Culture) ?? "DefaultEventType_Exam";
    public static string DefaultEventType_Homework => ResourceManager.GetString("DefaultEventType_Homework", Culture) ?? "DefaultEventType_Homework";
    public static string DefaultEventType_Holidays => ResourceManager.GetString("DefaultEventType_Holidays", Culture) ?? "DefaultEventType_Holidays";
    public static string DefaultEventType_Birthday => ResourceManager.GetString("DefaultEventType_Birthday", Culture) ?? "DefaultEventType_Birthday";
    public static string DefaultEventType_Appointment => ResourceManager.GetString("DefaultEventType_Appointment", Culture) ?? "DefaultEventType_Appointment";
    public static string DefaultEventType_Other => ResourceManager.GetString("DefaultEventType_Other", Culture) ?? "DefaultEventType_Other";
    public static string PageTitle => ResourceManager.GetString("PageTitle", Culture) ?? "PageTitle";
    public static string CalendarTitle => ResourceManager.GetString("CalendarTitle", Culture) ?? "CalendarTitle";
    public static string MonthView => ResourceManager.GetString("MonthView", Culture) ?? "MonthView";
    public static string WeekView => ResourceManager.GetString("WeekView", Culture) ?? "WeekView";
    public static string NewEvent => ResourceManager.GetString("NewEvent", Culture) ?? "NewEvent";
    public static string EditEvent => ResourceManager.GetString("EditEvent", Culture) ?? "EditEvent";
    public static string EventTitle => ResourceManager.GetString("EventTitle", Culture) ?? "EventTitle";
    public static string EventType => ResourceManager.GetString("EventType", Culture) ?? "EventType";
    public static string AllDay => ResourceManager.GetString("AllDay", Culture) ?? "AllDay";
    public static string TimeFrom => ResourceManager.GetString("TimeFrom", Culture) ?? "TimeFrom";
    public static string TimeTo => ResourceManager.GetString("TimeTo", Culture) ?? "TimeTo";
    public static string Save => ResourceManager.GetString("Save", Culture) ?? "Save";
    public static string Cancel => ResourceManager.GetString("Cancel", Culture) ?? "Cancel";
    public static string NoEvents => ResourceManager.GetString("NoEvents", Culture) ?? "NoEvents";
    public static string NoEventsThisWeek => ResourceManager.GetString("NoEventsThisWeek", Culture) ?? "NoEventsThisWeek";
    public static string ConfirmDeleteTitle => ResourceManager.GetString("ConfirmDeleteTitle", Culture) ?? "ConfirmDeleteTitle";
    public static string ConfirmDeleteEvent => ResourceManager.GetString("ConfirmDeleteEvent", Culture) ?? "ConfirmDeleteEvent";
    public static string Yes => ResourceManager.GetString("Yes", Culture) ?? "Yes";
    public static string No => ResourceManager.GetString("No", Culture) ?? "No";
    public static string EventTypeSettings => ResourceManager.GetString("EventTypeSettings", Culture) ?? "EventTypeSettings";
    public static string NewEventType => ResourceManager.GetString("NewEventType", Culture) ?? "NewEventType";
    public static string Color => ResourceManager.GetString("Color", Culture) ?? "Color";
    public static string Name => ResourceManager.GetString("Name", Culture) ?? "Name";
    public static string IsDefaultType => ResourceManager.GetString("IsDefaultType", Culture) ?? "IsDefaultType";
    public static string ExportIcs => ResourceManager.GetString("ExportIcs", Culture) ?? "ExportIcs";
    public static string ExportSuccess => ResourceManager.GetString("ExportSuccess", Culture) ?? "ExportSuccess";
    public static string ExportFailed => ResourceManager.GetString("ExportFailed", Culture) ?? "ExportFailed";
    public static string OpenLinkedExam => ResourceManager.GetString("OpenLinkedExam", Culture) ?? "OpenLinkedExam";
    public static string AlsoDeleteLinkedExam => ResourceManager.GetString("AlsoDeleteLinkedExam", Culture) ?? "AlsoDeleteLinkedExam";
    public static string TitleRequired => ResourceManager.GetString("TitleRequired", Culture) ?? "TitleRequired";
    public static string TimeToBeforeTimeFrom => ResourceManager.GetString("TimeToBeforeTimeFrom", Culture) ?? "TimeToBeforeTimeFrom";
    public static string EventTypeInUse => ResourceManager.GetString("EventTypeInUse", Culture) ?? "EventTypeInUse";
    public static string ConfirmDeleteEventType => ResourceManager.GetString("ConfirmDeleteEventType", Culture) ?? "ConfirmDeleteEventType";
    public static string NoType => ResourceManager.GetString("NoType", Culture) ?? "NoType";
    public static string Weekday_Mon => ResourceManager.GetString("Weekday_Mon", Culture) ?? "Weekday_Mon";
    public static string Weekday_Tue => ResourceManager.GetString("Weekday_Tue", Culture) ?? "Weekday_Tue";
    public static string Weekday_Wed => ResourceManager.GetString("Weekday_Wed", Culture) ?? "Weekday_Wed";
    public static string Weekday_Thu => ResourceManager.GetString("Weekday_Thu", Culture) ?? "Weekday_Thu";
    public static string Weekday_Fri => ResourceManager.GetString("Weekday_Fri", Culture) ?? "Weekday_Fri";
    public static string Weekday_Sat => ResourceManager.GetString("Weekday_Sat", Culture) ?? "Weekday_Sat";
    public static string Weekday_Sun => ResourceManager.GetString("Weekday_Sun", Culture) ?? "Weekday_Sun";
}
