//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DayDash.Modules.Calendar.Resources {
    using System;
    using System.Reflection;


    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CalendarResources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CalendarResources() {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DayDash.Modules.Calendar.Resources.CalendarResources", typeof(CalendarResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }

        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }

        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }

        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }

        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }

        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }

        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }

        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
    }
}